### ISSUE TITLE
Secure AWS S3 bucket partops contains production SSL certificates

### ISSUE THREAD

**Issue by Krijger** [part-up/partops#10]
Put them there manually.

**Comment by Krijger** [comment]
Specifically: put them in https://console.aws.amazon.com/s3/home?region=eu-west-1#&bucket=partops&prefix=certificates/

**Comment by wouterd** [comment]
partup_star.crt contains the full certificate + chain
partup_star.key contains the private key for the cert.

**Comment by Krijger** [comment]
Verified.
Also deleted old certificates from the bucket.
