### ISSUE TITLE
Share ci code for Jenkins jobs part-up master/develop/features

### ISSUE THREAD

**Issue by Krijger** [part-up/partops#12]
Only develop now uses ci.sh, leading to differences in setup and code maintained on Jenkins. E.g. the versions of the Meteor builder image are currently 1.2, 1.3 and 1.3.2, where some jobs do something with cache, and others not.

**Comment by Krijger** [comment]
Also, is https://jenkins.part-up.com/job/Part-up%20website%20build%20a%20branch./ not simply deprecated?

**Comment by Krijger** [comment]
https://jenkins.part-up.com/job/Part-up%20website%20tags/ is functionaly subset of develop, because ci.sh also updates a tagged image. Proposal: include the part about tagging in the ci.sh called by all jobs, because a tag is a tag is a tag is a tag.

**Comment by Krijger** [comment]
@wouterd ping

1. do you agree we can clean this up?
1. What is the code about meteor cache in https://jenkins.part-up.com/job/Part-up%20website%20features/configure about?

**Comment by wouterd** [comment]
This is pretty much all done. ci.sh is the only thing called. We might want to switch to Jenkinsfiles.
