### ISSUE TITLE
Create an AMI for our Neo4j

### ISSUE THREAD

**Issue by wouterd** [part-up/partops#3]
Based on the [UBCF-algorithm repo](https://github.com/part-up/UBCF-algorithm), create an AMI that can be started as our graph database for recommendations.

gradle -> deb -> ami?

Using nebula-ospackage-plugin?
https://nebula-plugins.github.io/documentation/introduction_to_nebula.html
https://github.com/Netflix/aminator or packer
https://github.com/nebula-plugins/gradle-ospackage-plugin

**Comment by Krijger** [comment]
Cancelled - although very interesting the problems we are trying to solve (that seemingly had to do with IO in the containers, but actually were related to the kernel call made by Neo4J to find out the available memory) are solved, making this issue worthless.
