### ISSUE TITLE
Tag selection for staging environments is flakey

### ISSUE THREAD

**Issue by wouterd** [part-up/partops#4]
Docker Hub doesn't properly report all tags of an image when there are lots of tags.
Find another way to detect whether tags of a certain image exist.
And fix the ci script of staging-envs.

**Comment by Krijger** [comment]
Something environment specific is going horribly and unexplainably wrong.

During a [Jenkins build](https://jenkins.part-up.com/job/Deploy%20or%20Refresh%20a%20staging%20environment/423/console) on a slave there is an error 
```
jq: error (at <stdin>:1): Cannot index number with string "token"
parse error: Invalid numeric literal at line 1, column 9
jq: error (at <stdin>:1): Cannot index number with string "token"
parse error: Invalid numeric literal at line 1, column 9
Meteor @ master, API @ master
```
I believe this error occurs while executing
```
token=$(http --body --follow "${token_request}" | jq --raw-output '.token')
```
where `token_request` is `https://auth.docker.io/token?service=registry.docker.io&scope=repository:partup/partup:pull,push`

Now, the weird thing is that if you perform the steps
1. ssh onto the ci server
2. `docker run --rm -i -t partup/docker-cloud-jenkins-slave sh` (using sh or bash yields the same results, but I have updated the Jenkins job with a bash tag)
3. using the output of the build you can verify the versions of `jq`, `bash` and `httpie` are the same => conclusion is that the build indeed runs in a `partup/docker-cloud-jenkins-slave` container
4. install `vim` to create the files `ci.sh` and `bash-functions/docker-hub-v2-api-requests.sh` to be equal to actual [ci.sh](https://github.com/part-up/staging-envs/blob/master/ci.sh) and [docker-hub-v2-api-requests.sh](https://github.com/part-up/staging-envs/blob/master/bash-functions/docker-hub-v2-api-requests.sh) and make `ci.sh` executable
5. execute `GIT_BRANCH=develop ./ci.sh`

you will see that the output is as expected, with the meteor tag of develop found!
```
# GIT_BRANCH=develop ./ci.sh   
Branch = develop
Finding the right image tags...
Meteor @ develop, API @ master
Make sure an S3 bucket is dedicated to the staging environment
Creating bucket s3://develop.images.part-up.com
make_bucket failed: s3://develop.images.part-up.com/ Unable to locate credentials
```

So, what the f can be happening here? @wouterd do you have an idea?

**Comment by Krijger** [comment]
So I was thinking it could be something with the SSH connection - that is the only difference between how the Jenkins Docker Plugin does stuff and I did it manually as described above. To reproduce this I wanted to run `/usr/sbin/sshd -D` in the slave container which the plugin documents that it does. However - no such file exists. I'm getting a bit lost on this part of the build architecture...

**Comment by wouterd** [comment]
Not using SSH for the docker slaves, it does something else. :)

**Comment by Krijger** [comment]
It would be nice to know what it does to reproduce the problem at hand...

**Comment by wouterd** [comment]
AFAIK it just starts a new container for each build and uses the command to kick off a certain script. It doesn't need to SSH into the instance that way.

**Comment by wouterd** [comment]
Fixed by replacing a bunch of bash by a bunch of go. :-)
